### ISSUE TITLE
pnfrag unable to parse example + petri net export is buggy

### ISSUE THREAD

**Issue by AdamBanham** [AdamBanham/koalas#15]
I have been working with pnfrag to ``quickly'' make a normative model but have run into to several issues:
- The example in `pmkoalas.models.pnfrag` does not work or produce the net as expected
- Further, labels for transitions must be one word without space
- Further, ids for places are not as expected 

Running the example results in this error:
```
Traceback (most recent call last):
  File "C:\Users\n7176546\OneDrive - Queensland University of Technology\phd\mypapers\2023\B\data\roadfines\gen_normative_model.py", line 36, in <module>
    test(debug=True,debug_level=DEBUG)
  File "C:\Users\n7176546\AppData\Local\Programs\Python\Python311\Lib\site-packages\pmkoalas\_logging.py", line 85, in wrapped
    val = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\n7176546\OneDrive - Queensland University of Technology\phd\mypapers\2023\B\data\roadfines\gen_normative_model.py", line 25, in test
    net1 = pnfrag.create_net()
           ^^^^^^^^^^^^^^^^^^^
TypeError: create_net() missing 2 required positional arguments: 'net_title' and 'net_text'
```

Having labels limited to a single word without space is a bit annoying, so I suggest extending that and including a break symbol so that looking for weights and such can be identified. Some examples of the new format for frags are below:
```python3
from pmkoalas.models.pnfrag import parse_net_fragments
from pmkoalas.models.petrinet import export_net_to_pnml

net = parse_net_fragments(
        "ROAD FINES NORMATIVE MODEL",
        "I -> [Create Fine |] -> p__1 -> [tau] -> F",
        "I -> [Create Fine] -> p__1 -> [tau] -> F",
        "I -> [Create Fine] -> p__1 -> [tau      |] -> F",
    )
    print(net)
    export_net_to_pnml(net, MODEL_OUT)
```
outputted model:
```
LabelledPetriNet with name of 'ROAD FINES NORMATIVE MODEL'
        Places:
                - (F(4))
                - (I(1))
                - (p(1))
        Transitions:
                - [tau(3) 1.0]
                - [Create Fine(2) 1.0]
        Arcs:
                - (p(1)) -> [tau(3) 1.0]
                - [Create Fine(2) 1.0] -> (p(1))
                - (I(1)) -> [Create Fine(2) 1.0]
                - [tau(3) 1.0] -> (F(4))
```

In the process of debugging, I also imported the partly working output into ProM and noticed some oddities:
- ProM visualisers do not see silent transitions as silent
- The exported pnml was not valid, when parsed by ProM

The exporting issue was due an additional comma in a line.

**Comment by adamburkegh** [comment]
Fixed the example in this commit https://github.com/AdamBanham/koalas/commit/8335933793e221f7f0c9706fd3f020f55d1b13de

**Comment by adamburkegh** [comment]
Place labels like `p1` do work in the current code (even before the commit). `p__1` is for distinguishing places or transitions with duplicate labels. In `p__1` vs `p__2`, they share the `p` label but are distinct places.

The doc comment example issues with `create_net()` not having default parameters were a real problem though. Thanks for flagging.

The white space in labels might be nice.

**Comment by AdamBanham** [comment]
The connected PR has a working impl for white space.
