### ISSUE TITLE
Silent property in Petri net export

### ISSUE THREAD

**Issue by adamburkegh** [AdamBanham/koalas#18]
Currently exported Petri nets will not show silent transitions as silent in ProM (and possibly other tools).

This can be a painful issue to deal with downstream as it's not just visibility - programmatic checking of the silent property will also fail. It will treat the transitions as a normal transition with the label "tau". The PNML property is called "invisible" not "silent".

This was mentioned in issue #15 by @AdamBanham.

I got burnt by this with my Haskell petri net library, here is a code snippet that includes the fix.

```haskell
instance (Show a, Ord a, Typeable a) => XMLOutput (WTransition a) where
    toXML (WTransition x nodeId w sil) idStr = 
        element "transition" (idAttr nodeId) 
                [Elem (nameNode x), 
                 Elem $ element "toolspecific"
                         spnToolAttrs
                         [propertyNode "distributionType" "IMMEDIATE",
                          propertyNode "weight" (show w),
                          propertyNode "invisible" (show sil),
                          propertyNode "priority" "1" ] ] 
```

This commit 
https://github.com/adamburkegh/toothpaste/commit/ef15f95a72a95bb16c4f92e940778a28d54d9b57

**Comment by AdamBanham** [comment]
fixed in #16
