### ISSUE TITLE
Petri Nets and Model Module

### ISSUE THREAD

**Issue by AdamBanham** [AdamBanham/koalas#2]
We need a defined object for handling Petri Net construction and WF-Net construction. Placing these include a module called models, would be nice.

Completing this might include the following:

- A new module called models
- A PetriNet Object
- A WorkFlow Object (subclass of PetriNet)
- An export function to pnml
- A marking function
- reachability?
- soundness?
- liveness?
- bounded?

**Comment by adamburkegh** [comment]
See #8
